### ISSUE TITLE
Website not Responding

### ISSUE THREAD

**Issue by MBoegers** [SANSA-Stack/Archived-SANSA-Stack#6]
Hi,
the project's website (sansa-stack.net) has an internal server error since a few days.
I would like to use SANSA in my theses but without a responding webpage, it is hard ;-)

Firefox loading terminates with an empty page and wget returns 500 
```bash
$ wget www.sansa-stack.net
[...] 500 Internal Server Error 2020-03-25 14:38:25 FEHLER 500: Internal Server Error.
```

Best Merlin

**Comment by patrickwestphal** [comment]
Hi Merlin,

sorry for the late reply and many thanks for reporting. The website should be up again.

Best regards,
Patrick
